config/routes.rb
Rails.application.routes.draw do
  
  resources :menu
  devise_for :users, controllers: { registrations: 'users/registrations' }
  

end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
  before_filter :authenticate_user!
  
  
  def new
    @menu_item = MenuItem.new
  end


  def create
    @menu_item = MenuItem.new(menu_params)
    user = current_user.id
    @menu_item.user_id = user
    build_your_own = params["menu_item"]["is_build_your_own"]
    
    if build_your_own == "1" and @menu_item.save      
      
      new_groups = params["menu_group_num"]
      
      for i in 0..new_groups.length - 1
        group_name = params["group_name_" + new_groups[i]]
        group_price = params["additional_price_" + new_groups[i]]
        group_max = params["max_allowed_" + new_groups[i]]
        menu_group = MenuItemContentGroup.create(MenuItem_id: @menu_item.id, name: group_name, additional_price: group_price, max_allowed: group_max)
        
        menu_group_content = params["menuitemcontent" + new_groups[i]]
        
        for j in 0..menu_group_content.length - 1
          MenuItemContent.create(MenuContentGroup_id: menu_group.id, ingredient: menu_group_content[j])
        end
      end
    
    elsif @menu_item.save
        format.html { redirect_to bid_path(@menu_item.id), notice: 'Menu Item was successfully submitted.' }
        format.json { render :show, status: :created, location: @menu_item }
    else
        format.html { render :new }
        format.json { render json: @menu_item.errors, status: :unprocessable_entity }
    end
  end

  
  def edit
    @menu_item = MenuItem.find_by!(id: params[:id], user_id: current_user.id)
  end
  
  
  def update
    @menu_item = MenuItem.find_by!(id: params[:id], user_id: current_user.id)
    build_your_own = @menu_item.is_build_your_own
    
    if @menu_item.update(menu_params)
      
      #If not build your own remove all groups
      if build_your_own and !@menu_item.is_build_your_own
        @menu_item.delete_groups()
      end
      
      if @menu_item.is_build_your_own
        removed_groups = params["removed_record"]
        @menu_item.remove_groups(removed_groups)
        
        removed_content = params["removed_content"]
        @menu_item.remove_content(removed_content)
        
        menu_groups = @menu_item.MenuItemContentGroup.where(is_deleted: false)
        group_ids = params["group_id"]
        #update existing groups
        for i in 0..group_ids.size - 1
          begin
            menu_group = menu_groups.find(group_ids[i])
            menu_group.update(name: params["group_name_" + menu_group.id.to_s], max_allowed: params["max_allowed_" + menu_group.id.to_s], additional_price: params["additional_price_" + menu_group.id.to_s])
            menu_content = menu_group.MenuItemContent.where(is_deleted: false)
            
            #Update existing content
            for content in menu_content
              content.update(ingredient: params["menuitemcontent" + content.id.to_s])
            end
            
            #Add new content to group
            new_content = params["menuitemcontente" + menu_group.id.to_s]
            if new_content
              for j in 0..new_content.size - 1
                  MenuItemContent.create(MenuContentGroup_id: menu_group.id, ingredient: new_content[j])
              end
            end
          rescue ActiveRecord::RecordNotFound
          end
        end
        
        #Add new groups
        new_groups = params["menu_group_num"]
        if new_groups
          for i in 0..new_groups.count - 1
            group_name = params["group_name_" + new_groups[i].to_s]
            group_price = params["additional_price_" + new_groups[i].to_s]
            group_max = params["max_allowed_" + new_groups[i].to_s]
            menu_group = MenuItemContentGroup.create(MenuItem_id: @menu_item.id, name: group_name, additional_price: group_price, max_allowed: group_max)
            
            menu_group_content = params["menuitemcontent" + new_groups[i].to_s]
            
            for j in 0..menu_group_content.length - 1
              MenuItemContent.create(MenuContentGroup_id: menu_group.id, ingredient: menu_group_content[j])
            end
          end
        end
      end
    end
  end
  
  
  def show
      @menu_items = MenuItem.where(id: params[:id], is_deleted: false)
  end


  def index
    @menu_items = MenuItem.where(user_id: current_user.id, is_deleted: false)  
  end
  
  
  def destroy
    @menu_item = RequestCar.find_by!(:id=>params[:id], :user_id=>current_user.id)
    if @menu_item.present?
      @menu_item.is_deleted = false
    end
    respond_to do |format|
      format.html { redirect_to '/menu', notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  
  private

  def menu_params
    params.require(:menu_item).permit(:name, :description, :price, :is_build_your_own)
  end
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/views/menu/_show.html.erb
<% @menu_items.each do |menu_item| %>
<div class="card-menu-item col-sm-3">
  <img class="card-img-top" src="http://barcodedc.com/wp-content/gallery/food/healthfitnessrevolution-com.jpg" alt="Card image cap">
  <div class="card-block">
  	<span id="card-price-wrapper"><h4>$ <%= menu_item.price %></h4></span>
    <h4 class="card-title"><%= menu_item.name%></h4>
    <p class="card-text"><%= menu_item.description%></p>
	<div class="card-btn-wrapper">
	    <a href="#" class="btn btn-primary">Details</a>
		<% if show_action and current_user.id == menu_item.user_id %>
			<a href="<%= edit_menu_path(menu_item.id) %>" class="btn btn-info">Edit</a>
			<%= link_to "Delete", menu_path(menu_item), class: "btn btn-danger", method: :delete, data: { confirm: 'Are you certain you want to delete this?' } %>
		<% end %>
	</div>
  </div>
</div>
<% end %>

app/views/menu/edit.html.erb
<div class="col-md-8">
<%= simple_form_for @menu_item, url: menu_path(@menu_item.id), html: { id: :edit_order }  do |f| %>
	<%= f.input :name, label: "Menu Item Name*", label: "Menu Item Name", :input_html => { data: {req: '1'}} %>
	<%= f.input :description, label: "Description*", as: :text, :input_html => { data: {req: '1'}} %>
	<%= f.input :price, label: "Price*", :input_html => { data: {req: '1'}} %>				
	<%= f.input :is_build_your_own, label: "Build Your Own",  :input_html => {:id => "build_your_own"} %>
	
	<% if @menu_item.is_build_your_own %>
		<% @menu_item.MenuItemContentGroup.each_with_index do |group, index| %>
		<% if !group.is_deleted %>
		<div id = "build_your_own_content_edit">
			<div class="panel panel-default">
			    <div class="panel-heading" role="tab" id="heading<%= group.id %>">
			      <h4 class="panel-title">
			        <a data-groupid="<%= group.id %>" role="button" id="rm-btn-<%= group.id %>" class="btn btn-danger rm-btn action-btn" data-toggle="collapse" data-parent="#accordion" href="#collapse<%= group.id %>" aria-expanded="true" aria-controls="collapse<%= group.id %>">
			          Remove
			        </a>
			      </h4>
				  <input type = "hidden" name = "removed_record[]" id="rm-record-<%= group.id %>"/>
			    </div>
			    <div id="collapse<%= group.id %>" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading<%= group.id %>">
			      <div class="panel-body">
					<div class="form-inline">
						<input type = "hidden" name="group_id[]" value="<%= group.id %>"/>
						<b>Name*</b>
						<input data-req="1" name="group_name_<%= group.id %>" value="<%= group.name %>" class="string optional form-control" type="text"/>
						<b>Price*</b>
						<input data-req="1" name="additional_price_<%= group.id %>" value="<%= group.additional_price %>" class="string optional form-control" type="text"/>
						<b>Maximum Allowed*</b>
						<input data-req="1" name="max_allowed_<%= group.id %>" value="<%= group.max_allowed %>" class="string optional form-control" type="text"/>
					</div>
					<br/>
					<b>Menu Item Content</b>
					<% group.MenuItemContent.each do |ing| %>
						<% if !ing.is_deleted %>
							<div class="col-md-11">
								<input type="hidden" name="removed_content[]" id="rm-content-inp-<%= ing.id %>"/>
								<input id="ing-content-<%= ing.id %>" name="menuitemcontent<%= ing.id %>" value="<%= ing.ingredient %>" placeholder="Name" type="text" class="string optional form-control ing-input"/>
								<span id="rm-btn-disp-<%= ing.id %>" onclick="removeContentEdit(<%= ing.id %>)" class="glyphicon glyphicon-remove inline"></span>
								<span id="add-btn-disp-<%= ing.id %>" onclick="undoRemoveContentEdit(<%= ing.id %>)" style="display: none;" class="glyphicon glyphicon-ok inline"></span>
							</div>
							<br/>
						<% end %>
					<% end %>
					<div class="col-md-11"><span id="add-new-rowe<%= group.id %>"></span></div>
					<a class="btn" onclick="addContentRow('e<%= group.id %>')">+ Add Choice</a>
				 </div>
				</div>
			</div>
		</div>
		<% end %>
		<% end %>
	<% end%>
	<div id="add-new-option"></div>
	<a class="btn" onclick="addGroupRow()">+ Add Option</a>
	<%= f.button :submit ,  "Submit", class: "btn btn-primary" %>
<% end %>
</div>

<script>
	var num_groups = <%= @menu_item.MenuItemContentGroup.count %>;
	$("#edit_order").submit(function (event) {
		if (!validateFormInputs("edit_order")){
			event.preventDefault();
		}
	});
	$(document).ready(function() {
		$(".action-btn").click(function() {
			var group_id = $(this).data("groupid");
			var class_name = $(this).attr("class");
			if (class_name.indexOf("rm-btn") != -1) {
				$(this).addClass('add-btn btn-success').removeClass('rm-btn btn-danger');
				$(this).text("Undo");
				$("#rm-record-"+group_id).val(group_id);
			}
			else if (class_name.indexOf("add-btn") != -1) {
				$(this).addClass('rm-btn btn-danger').removeClass('add-btn btn-success');
				$(this).text("Remove");
				$("#rm-record-"+group_id).val("");
			}
		});
	});
	
	function undoRemoveContentEdit(id) {
		$("#ing-content-" + id).prop('disabled', false);
		$("#rm-content-inp-" + id).val("");
				
		$("#add-btn-disp-" + id).css({
			display: 'none'
		});		
		
		$("#rm-btn-disp-" + id).css({
			display: 'block'
		});
	}
	function removeContentEdit(id) {
		$("#ing-content-" + id).prop('disabled', true);
		$("#rm-content-inp-" + id).val(id);
		$("#rm-btn-disp-" + id).css({
			display: 'none'
		});
		
		$("#add-btn-disp-" + id).css({
			display: 'block'
		});
	}
</script>

<%= javascript_include_tag 'menujs' %>

app/views/menu/index.html.erb
<%= render partial: "show", collections: @menu_item, locals: { show_action: true } %>

app/views/menu/new.html.erb
<div class="col-md-8">
	<%= simple_form_for @menu_item, url: '/menu'  do |f| %>
		<%= f.input :name, label: "Menu Item Name*", :input_html => { data: {req: '1'}} %>
		<%= f.input :description, label: "Description*", as: :text, :input_html => { data: {req: '1'}} %>
		<%= f.input :price, label: "Price*", :input_html => { data: {req: '1'}} %>				
		<%= f.input :is_build_your_own, label: "Build Your Own",  :input_html => {:id => "build_your_own"} %>
	
		<div id = "build_your_own_content">
			<div class="panel panel-default">
			    <div class="panel-heading" role="tab" id="headingOne">
			      <h4 class="panel-title">
			        <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
			          Plate Options
			        </a>
			      </h4>
			    </div>
			    <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
			      <div class="panel-body">
			      	<div class="form-inline">
						<input type="hidden" name="menu_group_num[]" value="0"/>
						<b>Name*</b>
						<input data-req="1" name="group_name_0" class="string optional form-control" type="text"/>
						<b>Price*</b>
						<input data-req="1" name="additional_price_0" class="string optional form-control" type="text"/>
						<b>Maximum Allowed*</b>
						<input data-req="1" name="max_allowed_0" class="string optional form-control" type="text"/>
					</div>
					<br/>
					<b>Menu Item Content</b>
					<input data-req="1" name="menuitemcontent0[]" placeholder="Name" type="text" class="string optional form-control"/>
					<span id="add-new-row0"></span>
					<br/>
					<a class="btn" onclick="addContentRow(0)">+ Add Choice</a>
			      </div>
			    </div>
		  </div>
		  <div id="add-new-option"></div>
				
		 <a class="btn" onclick="addGroupRow()">+ Add Option</a>
		</div>
		
		<br/>
		<%= f.button :submit ,  "Submit", class: "btn btn-primary" %>
	<% end %>
	
</div>


<script>
	var num_groups = 1;
	
	$("#new_menu_item").submit(function (event) {
		if (!validateFormInputs("new_menu_item")){
			event.preventDefault();
		}
	});
</script>
<%= javascript_include_tag 'menujs' %>

app/views/menu/show.html.erb
<%= render partial: "show", collections: @menu_items, locals: { show_action: false } %>